/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package design_package;
import entities_package.Labor;
import entities_package.LabUser;
import dao_packages.LabUserDAO;
import dao_packages.LaborDAO;
import dao_packages.PresenceDAO;
/**
 *
 * @author MIKEL
 */
public class Pointage extends javax.swing.JFrame {
    
    private Labor laborActif;
    /**
     * Creates new form Pointage
     * @param labo
     */
    
    private void rafraichirOccupation() {
        try {
            LaborDAO laborDAO = new LaborDAO();
            PresenceDAO presDAO = new PresenceDAO();

            // 1. Compter les présents actuels
            int presents = laborDAO.getPresentsActuelsCount(laborActif.getIdLabo());
            int max = laborActif.getCapaciteMax();

            // 2. Calculer le pourcentage
            int pourcentage = (max > 0) ? (presents * 100 / max) : 0;

            // 3. Mettre à jour tes labels et ta jProgressBar
            // (Remplace les noms de variables ci-dessous par les nôtres si différents)
            placeBtn.setText(presents + " / " + max + " Places");
            occBtn.setText(pourcentage + " %");
            jProgressBar1.setMaximum(max);
            jProgressBar1.setValue(presents);

        } catch (Exception e) {
            System.out.println("Erreur jauge : " + e.getMessage());
        }
    }
    
    public Pointage(Labor labo) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.laborActif = labo;
        
        if (this.laborActif != null) {
            // Remplace lblNomLabo par le nom de ton JLabel de titre
            laboName.setText(laborActif.getNomLabo().toUpperCase());
        }
        
        rafraichirOccupation();
    }
    
    public Pointage(){
        initComponents();
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laboName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        placeBtn = new javax.swing.JLabel();
        occBtn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMatricule = new javax.swing.JTextField();
        cmbMotif = new javax.swing.JComboBox<>();
        validPrBtn = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        listeBtn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        addBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROJET DU COURS DE POO2 2026 - 2027");
        setResizable(false);

        laboName.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        laboName.setText("LABORATOIRE FTSI");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Occupation: ");

        placeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        placeBtn.setText("0 / 80 Places");

        occBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        occBtn.setText("0 %");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Matricule : ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Motif : ");

        txtMatricule.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtMatricule.setText("ETU001");
        txtMatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculeActionPerformed(evt);
            }
        });

        cmbMotif.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbMotif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Travail personnel", "Utilisation du materiel", "Travail Pratique", "Cours" }));

        validPrBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        validPrBtn.setText("VALIDER LE POINTAGE (Entrée/Sortie)");
        validPrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validPrBtnActionPerformed(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusLabel.setText("Bienvenue");

        listeBtn.setText("Liste de Présence");
        listeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Add Student");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Borne de Pointage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(txtMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addBtn))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(cmbMotif, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(validPrBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(occBtn)
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(placeBtn))
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(laboName, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(laboName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(occBtn)
                        .addComponent(jLabel1)
                        .addComponent(placeBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMatricule, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(cmbMotif))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validPrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listeBtn)
                    .addComponent(addBtn))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculeActionPerformed
        // TODO add your handling code here:
        validPrBtnActionPerformed(evt);
    }//GEN-LAST:event_txtMatriculeActionPerformed

    private void validPrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validPrBtnActionPerformed
        // TODO add your handling code here:                                           
            String matricule = txtMatricule.getText().trim();
            String motif = cmbMotif.getSelectedItem() != null ? cmbMotif.getSelectedItem().toString() : "Autre";

            // 1. Contrôle de saisie
            if (matricule.isEmpty()) {
                statusLabel.setText("Saisissez le Matricule SVP !");
                statusLabel.setForeground(java.awt.Color.RED);
                return;
            }

            try {
                LabUserDAO userDAO = new LabUserDAO();
                PresenceDAO presenceDAO = new PresenceDAO();

                // 2. Rechercher l'étudiant
                LabUser user = userDAO.findByMatricule(matricule);
                if (user == null) {
                    statusLabel.setText("Matricule " + matricule + " introuvable !");
                    statusLabel.setForeground(java.awt.Color.RED);
                    txtMatricule.selectAll();
                    return;
                }

                // 3. Effectuer le pointage (Entrée ou Sortie)
                String resultat = presenceDAO.pointer(user, laborActif, motif);

                // 4. Afficher le message sur ton JLabel (ex: lblStatus - ton label "Bienvenue")
                statusLabel.setText(resultat);
                if (resultat.startsWith("SORTIE")) {
                    statusLabel.setForeground(java.awt.Color.BLUE);
                } else if (resultat.startsWith("ENTRÉE")) {
                    statusLabel.setForeground(new java.awt.Color(0, 128, 0)); // Vert
                } else {
                    statusLabel.setForeground(java.awt.Color.RED);
                }

                // 5. Nettoyer le champ texte & rafraîchir la jauge d'occupation
                txtMatricule.setText("");
                txtMatricule.requestFocus();
                rafraichirOccupation();

            } catch (Exception e) {
                statusLabel.setText("Erreur BD : " + e.getMessage());
                statusLabel.setForeground(java.awt.Color.RED);
            }  
    }//GEN-LAST:event_validPrBtnActionPerformed

    private void listeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeBtnActionPerformed
        // TODO add your handling code here:
        Liste fenetreListe = new Liste(this.laborActif);
    
        // On l'affiche
        fenetreListe.setVisible(true);
    }//GEN-LAST:event_listeBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
                                                  
        AddStudent fenetreAjout = new AddStudent();
        fenetreAjout.setLocationRelativeTo(null);
        fenetreAjout.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        fenetreAjout.setVisible(true);
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pointage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> cmbMotif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel laboName;
    private javax.swing.JButton listeBtn;
    private javax.swing.JLabel occBtn;
    private javax.swing.JLabel placeBtn;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField txtMatricule;
    private javax.swing.JButton validPrBtn;
    // End of variables declaration//GEN-END:variables
}
